CREATE TABLE MessageStatus(
    Id INT NOT NULL,
    ContactId INT NOT NULL,
    MessageId INT NOT NULL,
    StatusId INT NOT NULL,
    [DateTime] DATETIME2 NOT NULL
);

CREATE TABLE Contact(
    Id INT NOT NULL,
    Nickname VARCHAR(128) NOT NULL
);

CREATE TABLE [Status] (
    Id INT NOT NULL,
    [Status] VARCHAR (20) NOT NULL
);

SELECT * FROM MessageStatus;

ALTER TABLE MessageStatus
    ADD CONSTRAINT PK_MessageStatus PRIMARY KEY CLUSTERED (Id);
ALTER TABLE Contact
    ADD CONSTRAINT PK_Contact PRIMARY KEY CLUSTERED (Id);
ALTER TABLE [Status]
    ADD CONSTRAINT PK_Status PRIMARY KEY CLUSTERED (Id);



ALTER TABLE MessageStatus
    ADD CONSTRAINT FK_ContactId_Contact FOREIGN KEY (ContactId)
    REFERENCES Contact (Id)
    ON DELETE NO ACTION
    ON UPDATE CASCADE;

ALTER TABLE MessageStatus
    ADD CONSTRAINT FK_StatusId_Status FOREIGN KEY (StatusId)
    REFERENCES [Status] (Id)
    ON DELETE NO ACTION
    ON UPDATE CASCADE;

DROP TABLE MessageStatus;
DROP TABLE Contact;
DROP TABLE [Status];